export const products = [
  {
    id: "1",
    name: "KX 450 F",
    price: '12.000 USD',
    img: "../img/cross-250f.png",
    category: "1",
  },
  {
    id: "2",
    name: "KX 250 F",
    price: '8.500 USD',
    img: "../img/cross-450f.png",
    category: "1",
  },
  {
    id: "3",
    name: "NINJA H2",
    price: '80.000 USD',
    img: "../img/sport-h2.png",
    category: "2",
  },
  {
    id: "4",
    name: "NINJA H2 SX SE",
    price: '65.000 USD',
    img: "../img/sport-ninja.png",
    category: "2",
  },
  {
    id: "5",
    name: "NINJA ZX-14-R",
    price: '100.000 USD',
    img: "../img/sport-zx.png",
    category: "2",
  },
  {
    id: "6",
    name: "VERSYS 650",
    price: '30.500 USD',
    img: "../img/street-versys650.png",
    category: "3",
  },
  {
    id: "7",
    name: "VERSYS 1000",
    price: '48.500 USD',
    img: "../img/street-versys1000.png",
    category: "3",
  },
];
